With mock keycloak user
entando/keycloak-commons pull request #4
Opened 2019-08-05 17:54 UTC by Kerruba

Split the keycloak-connector into 2 modules and add testutils classes to enable mock Keycloak access tokens with a dedicated annotation similar to `WithMockUser`

2019-08-05 17:55 UTC, entando-service commented
All is well

2019-08-06 08:36 UTC, entando-service commented
All is well

2019-08-06 08:46 UTC, ampie requested changes
It was a good idea to assist plugin developers with testing infrastructure. The project structure makes sense too. My only request is for  the .idea directory to be removed from git and added to .gitignore.

2019-08-06 09:23 UTC, entando-service commented
All is well

2019-08-06 10:47 UTC, entando-service commented
All is well

2019-08-06 11:06 UTC, entando-service commented
All is well

2019-08-06 11:14 UTC, sergiofilhowz reviewed
README and LICENSE files should be on root folder

2019-08-06 11:14 UTC, sergiofilhowz commented on .gitignore
> +../.idea/
I think this should be just .idea/

2019-08-06 11:14 UTC, sergiofilhowz commented on testutils/.gitignore
> +HELP.md
we should merge this file with the one on root

2019-08-06 12:26 UTC, entando-service commented
All is well

2019-08-06 12:29 UTC, entando-service commented
All is well

2019-08-06 12:50 UTC, entando-service commented
All is well

2019-08-06 14:35 UTC, sergiofilhowz approved these changes

2019-08-06 14:36 UTC, sergiofilhowz commented
looks good

2019-08-06 14:38 UTC, ampie approved these changes

2019-08-06 14:38 UTC, merged